Repository nextflow-io/nf-co2footprint, pull requests merged in 2025-07, with the labels that each got.

#243 Feature: Add new TDP table
  CHANGELOG.md
  NOTICE
  README.md
  docs/usage/parameters.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/DataMatrix.groovy
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/resources/cpu_tdp_data/CPU_TDP.csv
  plugins/nf-co2footprint/src/resources/cpu_tdp_data/CPU_TDP_wikichip.csv
  plugins/nf-co2footprint/src/resources/cpu_tdp_data/LICENSE
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/testResources/report_test.html
  plugins/nf-co2footprint/src/testResources/summary_test.txt
Labels: 🪲 bug

#253 Documentation: Changelog Version: 1.0.0-rc
  .github/ISSUE_TEMPLATE/bug_report.yaml
  CHANGELOG.md
  README.md
  docs/contributing/setup.md
  docs/usage/configuration.md
  plugins/nf-co2footprint/src/resources/META-INF/MANIFEST.MF
Labels: 🧼 cleanup

#256 Add 'default cloud' row to tdp table
  plugins/nf-co2footprint/src/resources/cpu_tdp_data/CPU_TDP_wikichip.csv
Labels: 🪲 bug, 🐁 small

#259 Feature: Better output of help request
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/CIValueComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/DataContainers/TDPDataMatrixTest.groovy
Labels: 📣 logging, 🐁 small

#262 Fix: Aligned style of expandable elements
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.css
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/FileCreators/CO2FootprintReportTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/TestHelper.groovy
  plugins/nf-co2footprint/src/testResources/file_checks.json
  plugins/nf-co2footprint/src/testResources/report_test.html
Labels: 🪲 bug, 🗄️ output

#269 Fix: Error logging on providing `customTDPTable`
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/DataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/TDPDataMatrix.groovy
Labels: 🛟 catches, 📣 logging, 🐁 small

#271 Fix/CI: CITATION.cff schema, Automated schema checking
  .github/workflows/validate-citations.yml
  CHANGELOG.md
  CITATION.cff
  README.md
Labels: 🪲 bug, 🐁 small, 🛰️ continuous integration

#272 Chore: 1.0.0 rc.2 version bump
  CHANGELOG.md
  README.md
  docs/contributing/setup.md
  docs/usage/configuration.md
  plugins/nf-co2footprint/src/resources/META-INF/MANIFEST.MF
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintFactoryTest.groovy
  plugins/nf-co2footprint/src/testResources/file_checks.json
  plugins/nf-co2footprint/src/testResources/report_test.html
  plugins/nf-co2footprint/src/testResources/summary_test.txt
Labels: 🐁 small

#276 Version bump 1.0.0 rc.3
  CHANGELOG.md
  CITATION.cff
  README.md
  docs/contributing/setup.md
  docs/usage/configuration.md
  plugins/nf-co2footprint/src/resources/META-INF/MANIFEST.MF
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintFactoryTest.groovy
  plugins/nf-co2footprint/src/testResources/file_checks.json
  plugins/nf-co2footprint/src/testResources/report_test.html
  plugins/nf-co2footprint/src/testResources/summary_test.txt
Labels: 🧼 cleanup, 🐁 small
