Repository nextflow-io/nf-co2footprint, pull requests merged in 2025-05, with the labels that each got.

#178 Feature: Add differentiation of computing machine type
  docs/usage/parameters.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintConfigTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
Labels: 💎 enhancement, 🐁 small

#187 CI: Contribution guideline & PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
  docs/contributing/guidelines.md
  docs/contributing/publishing.md
  docs/contributing/setup.md
  mkdocs.yml
Labels: 📝 documentation, 🐁 small, 🛰️ continuous integration

#192 Documentation: Update plugin documentation (using MkDocs)
  .gitignore
  README.md
  docs/co2footprint.md
  docs/co2footprint_calculation.md
  docs/index.md
  docs/usage/configuration.md
  docs/usage/output.md
  docs/usage/parameters.md
  mkdocs.yml
Labels: 📝 documentation

#205 Fix: Moved PR template
  .github/pull_request_template.md
Labels: 🐁 small, 🛰️ continuous integration

#204 Chore: Renamed server to 'compute cluster'
  plugins/nf-co2footprint/src/resources/CPU_TDP.csv
Labels: 🪲 bug, 🔀 refactor, 🐁 small

#206 Fix: Skip comparison to executor, when `''` is explicitly specified as `machineType`
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
Labels: 🪲 bug, 🐁 small

#201 Fix: Fixed HTML report rendering and improve time formatting
  README.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2EquivalencesRecord.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/Converter.groovy
  plugins/nf-co2footprint/src/resources/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/utils/ConverterTest.groovy
Labels: 💎 enhancement, 🗄️ output

#209 Fix: Correct display plane km
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintReportTest.groovy
Labels: 🪲 bug, 🐁 small, 🗄️ output

#210 Refactor: Moving call to get total Memory size
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
Labels: 🔀 refactor, 🐁 small

#181 Feature: Real-time Carbon intensity values from Electricity Maps API + Fallback
  NOTICE
  README.md
  docs/usage/parameters.md
  plugins/nf-co2footprint/build.gradle
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CIDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2Record.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CarbonIntensity.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintTrace.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/Converter.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/DataContainers.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/HelperFunctions.groovy
  plugins/nf-co2footprint/src/resources/CI_aggregated.v2.2.csv
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.js
  plugins/nf-co2footprint/src/resources/ci_data/LICENSE
  plugins/nf-co2footprint/src/resources/ci_data/ci_yearly_2024_by_location.csv
  plugins/nf-co2footprint/src/resources/cpu_tdp_data/CPU_TDP.csv
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintConfigTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CarbonIntensityTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/TDPDataMatrixTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/utils/DataContainersTest.groovy
Labels: 💎 enhancement, 🧼 cleanup, 🔀 refactor, 🛟 catches, 📣 logging, 🐘 big, 🧪 Testing

#203 Test: Checksum file testing
  CHANGELOG.md
  plugins/nf-co2footprint/build.gradle
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2Record.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CarbonIntensity.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/DataContainers.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintConfigTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/FileCreators/CO2FootprintReportTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/TestHelper.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/utils/DataContainersTest.groovy
Labels: 🧪 Testing

#217 Refactor: Deescalate access rights
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintReportSummary.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintResourcesAggregator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2Record.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/Converter.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/DataContainers.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/LoggingAdapters.groovy
Labels: 🧼 cleanup, 🔀 refactor, 🐁 small

#221 Feature: added EM API access date to HTML report
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
Labels: 📝 documentation, 🐁 small
