Repository nextflow-io/nf-co2footprint, pull requests merged in 2025-06, with the labels that each got.

#224 Logging to trace deescalation
  CHANGELOG.md
  docs/usage/output.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/LoggingAdapters.groovy
Labels: 🛟 catches, 🐁 small

#228 Delete COPYING file as it was redundant to LICENSE file in main repository
  COPYING
Labels: 🧼 cleanup, 🐁 small

#230 Fix unintended assignment to GString class
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/FileCreators/CO2FootprintReportTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/TDPDataMatrixTest.groovy
Labels: 🪲 bug, 🐁 small

#211 Fix: Custom tdp data checking, Feature: Updating TDPDataMatrix by merging custom matrix
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/DataContainers.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/TDPDataMatrixTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/utils/DataContainersTest.groovy
Labels: 🪲 bug, 💎 enhancement, 🛟 catches, 🐁 small

#234 Fix: removed '' machineType input option
  docs/usage/configuration.md
  docs/usage/parameters.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
Labels: ❔ question, 🐁 small

#236 docs: enhance code documentation and comments
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2EquivalencesRecord.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2Record.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintFile.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintSummary.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintTrace.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/Converter.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/DataContainers.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/HelperFunctions.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/LoggingAdapters.groovy
Labels: 📝 documentation, 🐁 small

#213 CI: Request warning reports
  .github/ISSUE_TEMPLATE/missing_chip.yaml
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/TDPDataMatrixTest.groovy
Labels: 🐁 small, 🛰️ continuous integration

#240 CI: Added to ignore in language display
  .gitattributes
Labels: 🐁 small, 🛰️ continuous integration

#237 Feature: Incorporating newly generated emissions (vs. cached) into the report
  CHANGELOG.md
  docs/usage/output.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2EquivalencesRecord.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2RecordAggregator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintSummary.groovy
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.css
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.js
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2ReportAggregatorTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/FileCreators/CO2FootprintReportTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/TestHelper.groovy
  plugins/nf-co2footprint/src/testResources/report_test.html
  plugins/nf-co2footprint/src/testResources/summary_test.txt
Labels: 📝 documentation, 🗄️ output

#238 Refactor: Categorizing folder structure & cleanup of empty files
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintFactory.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintReportSummary.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintResourcesAggregator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/BiMap.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/CIDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/CIValueComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/DataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/Matrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/TDPDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintSummary.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintTrace.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Records/CO2EquivalencesRecord.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Records/CO2Record.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Records/CO2RecordAggregator.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintConfigTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/DataContainers/CarbonIntensityTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/DataContainers/TDPDataMatrixTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/FileCreators/CO2FootprintReportTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/Records/CO2RecordAggregatorTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/utils/DataContainersTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/utils/LoggingTest.groovy
Labels: 🧼 cleanup, 🔀 refactor, 🐁 small

#239 Documentation: Added "How to cite" and adjusted credits
  CHANGELOG.md
  CITATION.cff
  README.md
  www.green-algorithms.org
Labels: 📝 documentation, 🐁 small

#242 Feature: Adds warning on `machineType == 'cloud'`
  CHANGELOG.md
  docs/usage/configuration.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
Labels: 📣 logging, 🐁 small
