Repository nextflow-io/nf-co2footprint, pull requests merged in 2025-08, with the labels that each got.

#285 Fix: CI options field for dynamic ci computation in summary
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintReport.groovy
Labels: 🐁 small, 🗄️ output

#292 Fix: Wrong memory fallback
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/HelperFunctions.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
Labels: 🪲 bug

#284 Fix: Ensure consistency between reports
  docs/usage/output.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintSummary.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreators/CO2FootprintTrace.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Records/CO2Record.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/Converter.groovy
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.js
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/FileCreators/CO2FootprintReportTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/Records/CO2RecordAggregatorTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/utils/ConverterTest.groovy
  plugins/nf-co2footprint/src/testResources/file_checks.json
  plugins/nf-co2footprint/src/testResources/report_test.html
  plugins/nf-co2footprint/src/testResources/summary_test.txt
Labels: 🧼 cleanup

#296 Refactor: Create report and summary file only `onFlowComplete`
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintObserver.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreation/BaseFileCreator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreation/ReportFileCreator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreation/SummaryFileCreator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreation/TraceFileCreator.groovy
Labels: 🪲 bug, 🗄️ output

#304 Refactor: Cleanup computer by removing unnecessary conversions
  CHANGELOG.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/CIDataMatrix.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/DataContainers/CIValueComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreation/ReportFileCreator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreation/SummaryFileCreator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Metrics/Converter.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Metrics/Quantity.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Records/CO2EquivalencesRecord.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Records/CO2Record.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/utils/HelperFunctions.groovy
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.js
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/FileCreation/ReportFileCreatorTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/Metrics/ConverterTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/Metrics/DataContainersTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/Metrics/QuantityTest.groovy
  plugins/nf-co2footprint/src/testResources/file_checks.json
  plugins/nf-co2footprint/src/testResources/report_test.html
Labels: 🧼 cleanup, 🔀 refactor

#307 Change CO2 to CO₂ in several files
  docs/co2footprint_calculation.md
  docs/index.md
  docs/usage/configuration.md
  docs/usage/output.md
  docs/usage/parameters.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/FileCreation/SummaryFileCreator.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/Records/CO2EquivalencesRecord.groovy
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.css
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.html
  plugins/nf-co2footprint/src/resources/assets/CO2FootprintReportTemplate.js
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintFactoryTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintObserverTest.groovy
  plugins/nf-co2footprint/src/testResources/file_checks.json
  plugins/nf-co2footprint/src/testResources/report_test.html
  plugins/nf-co2footprint/src/testResources/summary_test.txt
Labels: 🗄️ output

#306 Add cpuPowerModel option, make config & computer more readable
  CHANGELOG.md
  docs/usage/assets/example_cpuPowerModel.png
  docs/usage/parameters.md
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintComputer.groovy
  plugins/nf-co2footprint/src/main/nextflow/co2footprint/CO2FootprintConfig.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintComputerTest.groovy
  plugins/nf-co2footprint/src/test/nextflow/co2footprint/CO2FootprintConfigTest.groovy
Labels: 💎 enhancement, ✨ style
